# Travis-CI Build for Iceman Fork / Proxmark3
language: c

# Using trusty beta build environment,  based on Ubuntu 14.04
sudo: required
dist: trusty

#install:
compiler: gcc

## Install mainline ARM toolchain.  gcc-arm-none-eabi is available
## in Ubuntu >= 14.04, but this external PPA is needed for 12.04.
before_script:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - git fetch --all

#make command
script: "make all"